task1:
  func:
    - func/1.fc
  tests:
    - tests/tests1.fc

task2:
  func:
    - func/2.fc
  tests:
    - tests/tests2.fc

task3:
  func:
    - func/3.fc
  tests:
    - tests/tests3.fc

task4:
  func:
    - func/4.fc
  tests:
    - tests/tests4.fc

task5:
  func:
    - func/5.fc
  tests:
    - tests/tests5.fc
